name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-cache
          restore-keys: |
            ${{ runner.os }}-bun-cache

      - name: Install dependencies
        run: bun install

      - name: Check
        run: bun run check

      - name: Lint
        run: bun run lint
